title: Thanawich Juengkijthanawat
logo: /assets/head_.png
description: I am passionate about data science and the transformative power of AI, ML to solve real-world challenges, I am driven by the potential of turning raw data into valuable insights and scalable solutions. Proven by my hands-on experience in developing RAG chatbot, and predictive ML model.
show_downloads: True
theme: jekyll-theme-minimal
